# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  zen = {
    pname = "zen";
    version = "1.21.10b";
    src = fetchurl {
      url = "https://github.com/zen-browser/desktop/releases/download/1.21.10b/zen.linux-x86_64.tar.xz";
      sha256 = "sha256-ahNL79MOlhj01+UN3bOuch3hF7q3KKl8dfnlwhI6HQ8=";
    };
  };
}
