# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  zen = {
    pname = "zen";
    version = "1.18.8b";
    src = fetchurl {
      url = "https://github.com/zen-browser/desktop/releases/download/1.18.8b/zen.linux-x86_64.tar.xz";
      sha256 = "sha256-mv9Y6KwLmxNdV00BFUfvMiEzJI4TFYPk3g3q0WSbpVw=";
    };
  };
}
