# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  zen = {
    pname = "zen";
    version = "1.21.12b";
    src = fetchurl {
      url = "https://github.com/zen-browser/desktop/releases/download/1.21.12b/zen.linux-x86_64.tar.xz";
      sha256 = "sha256-R+FJK+3KWuQUL1SiIFWeC+96eE+1MJCPYFnadm0WIi8=";
    };
  };
}
